/* ErrandGo Ratings & Reviews — Play Store-style UI backed by Supabase. */
(function(){
const SUPABASE_URL='https://zynxoatmtnxtkxylxpqd.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5bnhvYXRtdG54dGt4eWx4cHFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc5MTkyOTQsImV4cCI6MjEwMzQ5NTI5NH0.M9eqkn8LlBqiNmAvRuIQ1zv8BwLIpFby1vb2TG0WWPU';
const api=SUPABASE_URL+'/rest/v1/';
function token(){try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(/-auth-token$/.test(k)){const v=JSON.parse(localStorage.getItem(k)||'null');if(v?.access_token)return v.access_token;}}}catch(e){}return''}
function hs(){const h={apikey:SUPABASE_KEY,'Content-Type':'application/json'},t=token();if(t)h.Authorization='Bearer '+t;return h}
async function get(p){const r=await fetch(api+p,{headers:hs()});if(!r.ok)throw new Error((await r.text()).slice(0,300)||'Request failed');return r.json()}
async function rpc(n,b){const r=await fetch(api+'rpc/'+n,{method:'POST',headers:hs(),body:JSON.stringify(b)}),t=await r.text();if(!r.ok)throw new Error(t.slice(0,500)||'Request failed');return t?JSON.parse(t):null}
async function me(){const t=token();if(!t)return null;const r=await fetch(SUPABASE_URL+'/auth/v1/user',{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+t}});return r.ok?r.json():null}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=d=>{try{return new Date(d).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}catch(e){return''}};
function stars(v){return `<span class="eg-stars">${[1,2,3,4,5].map(i=>`<span class="eg-star ${i<=v?'on':''}">★</span>`).join('')}</span>`}
function avg(rs){return rs.length?rs.reduce((a,r)=>a+Number(r.rating||0),0)/rs.length:0}
function summary(rs){const a=avg(rs);return `<div class="eg-rating-summary"><div class="eg-rating-score"><strong>${a.toFixed(1)}</strong>${stars(Math.round(a))}<small>${rs.length} review${rs.length===1?'':'s'}</small></div><div class="eg-rating-bars">${[5,4,3,2,1].map(n=>{const c=rs.filter(r=>Number(r.rating)===n).length,p=rs.length?Math.round(c/rs.length*100):0;return `<div><b>${n}</b><span><i style="width:${p}%"></i></span><small>${c}</small></div>`}).join('')}</div></div>`}
async function reviews(uid){const rs=await get(`reviews?reviewee_id=eq.${encodeURIComponent(uid)}&select=id,errand_id,reviewer_id,rating,comment,created_at&order=created_at.desc`);const ids=[...new Set(rs.map(r=>r.reviewer_id).filter(Boolean))];let ps=[];if(ids.length)ps=await get(`profiles?id=in.(${ids.map(encodeURIComponent).join(',')})&select=id,full_name,avatar_url`);const pm=Object.fromEntries(ps.map(p=>[p.id,p]));const out=[];for(const r of rs){let reply=null;try{const x=await get(`review_replies?review_id=eq.${encodeURIComponent(r.id)}&select=id,reply,created_at,updated_at&limit=1`);reply=x[0]||null}catch(e){}out.push({...r,reviewer:pm[r.reviewer_id]||{full_name:'ErrandGo user'},reply})}return out}
async function completed(uid){return get(`errands?or=(customer_id.eq.${uid},runner_id.eq.${uid})&status=eq.completed&select=id,title,customer_id,runner_id,completed_at&order=completed_at.desc&limit=30`)}
async function reviewed(uid){const x=await get(`reviews?reviewer_id=eq.${encodeURIComponent(uid)}&select=errand_id`);return new Set(x.map(r=>r.errand_id))}
function initials(n){return esc((n||'E').trim().charAt(0).toUpperCase()||'E')}
function render(root,uid,rs,es,done){const a=avg(rs);root.innerHTML=`<section class="eg-review-section"><div class="eg-review-heading"><div><small>COMMUNITY FEEDBACK</small><h3>Ratings & reviews</h3></div><span class="eg-review-badge">${a.toFixed(1)} ★</span></div>${summary(rs)}${es.length?`<div class="eg-rate-panel"><b>Rate your completed errands</b><small>Share your experience with the person you worked with.</small><div class="eg-rate-list">${es.map(e=>{const reviewee=e.customer_id===uid?e.runner_id:e.customer_id;if(!reviewee)return'';return `<article class="eg-rate-row"><div><b>${esc(e.title||'Completed errand')}</b><small>${date(e.completed_at)} · ${e.customer_id===uid?'Rate your runner':'Rate the requester'}</small></div>${done.has(e.id)?'<span class="eg-reviewed">Reviewed ✓</span>':`<button class="eg-open-rate" data-errand="${e.id}" data-reviewee="${reviewee}">Rate</button>`}</article>`}).join('')}</div></div>`:''}<div class="eg-review-list">${rs.length?rs.map(r=>`<article class="eg-review-card" data-review-id="${r.id}"><div class="eg-review-top"><div class="eg-review-person"><span class="eg-avatar">${initials(r.reviewer.full_name)}</span><div><b>${esc(r.reviewer.full_name)}</b><small>${date(r.created_at)}</small></div></div>${stars(Number(r.rating))}</div>${r.comment?`<p>${esc(r.comment)}</p>`:'<p class="eg-muted">No written review.</p>'}${r.reply?`<div class="eg-owner-reply"><b>Your response</b><p>${esc(r.reply.reply)}</p><small>${date(r.reply.updated_at||r.reply.created_at)}</small></div>`:''}<div class="eg-reply-slot"></div></article>`).join(''):'<div class="eg-empty-reviews"><div class="eg-mini-star">★</div><b>No reviews yet</b><p>Real ratings and written reviews will appear here after completed errands.</p></div>'}</div></section>`;
root.querySelectorAll('.eg-open-rate').forEach(b=>b.onclick=()=>modal(uid,b.dataset.errand,b.dataset.reviewee));
root.querySelectorAll('.eg-review-card').forEach(c=>replyBox(c.querySelector('.eg-reply-slot'),c.dataset.reviewId));}
function modal(uid,eid,rid){if(document.querySelector('.eg-review-modal'))return;const m=document.createElement('div');m.className='eg-review-modal';m.innerHTML=`<div class="eg-modal-backdrop"></div><div class="eg-modal-card" role="dialog" aria-modal="true"><button class="eg-modal-close">×</button><small>YOUR EXPERIENCE</small><h3>Rate this person</h3><p>How was your experience with this errand?</p><div class="eg-big-stars">${[1,2,3,4,5].map(i=>`<button type="button" data-big-star="${i}">★</button>`).join('')}</div><textarea maxlength="1000" placeholder="Write a review (optional)"></textarea><div class="eg-char">0 / 1000</div><button class="limeBtn eg-submit-review" disabled>Post review</button><div class="eg-modal-error"></div></div>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector('.eg-modal-close').onclick=close;m.querySelector('.eg-modal-backdrop').onclick=close;let rating=0;m.querySelectorAll('[data-big-star]').forEach(b=>b.onclick=()=>{rating=+b.dataset.bigStar;m.querySelectorAll('[data-big-star]').forEach(x=>x.classList.toggle('on',+x.dataset.bigStar<=rating));m.querySelector('.eg-submit-review').disabled=false});const ta=m.querySelector('textarea');ta.oninput=()=>m.querySelector('.eg-char').textContent=ta.value.length+' / 1000';m.querySelector('.eg-submit-review').onclick=async()=>{const b=m.querySelector('.eg-submit-review');b.disabled=true;b.textContent='Posting…';try{await rpc('submit_review',{p_errand_id:eid,p_reviewee_id:rid,p_rating:rating,p_comment:ta.value});close();await boot()}catch(x){m.querySelector('.eg-modal-error').textContent=x.message;b.disabled=false;b.textContent='Post review'}}}
function replyBox(slot,rid){if(!slot)return;slot.innerHTML=`<button class="eg-reply-toggle">Reply to this review</button><div class="eg-reply-editor" hidden><textarea maxlength="1000" placeholder="Write a public response..."></textarea><div><small>Only you can reply to a review about you.</small><button class="eg-send-reply">Reply</button></div><em></em></div>`;const ed=slot.querySelector('.eg-reply-editor');slot.querySelector('.eg-reply-toggle').onclick=()=>ed.hidden=!ed.hidden;slot.querySelector('.eg-send-reply').onclick=async()=>{const ta=ed.querySelector('textarea'),b=slot.querySelector('.eg-send-reply');if(!ta.value.trim())return;b.disabled=true;b.textContent='Sending…';try{await rpc('reply_to_review',{p_review_id:rid,p_reply:ta.value});await boot()}catch(e){ed.querySelector('em').textContent=e.message;b.disabled=false;b.textContent='Reply'}}}
async function boot(){const u=await me();if(!u)return;const page=(document.querySelector('.pageTitle')?.textContent||'')+' '+(document.querySelector('.content')?.textContent||'');if(!/\bprofile\b/i.test(page)||document.querySelector('#eg-review-widget'))return;const target=document.querySelector('.profileMenu')||document.querySelector('.profile.content');if(!target)return;const root=document.createElement('div');root.id='eg-review-widget';target.parentNode.insertBefore(root,target.nextSibling);try{const[rs,es,done]=await Promise.all([reviews(u.id),completed(u.id),reviewed(u.id)]);render(root,u.id,rs,es,done)}catch(e){root.innerHTML='<section class="eg-review-section"><div class="eg-review-error">Ratings could not be loaded right now. Please try again.</div></section>';console.error(e)}}
let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(boot,180)}).observe(document.body,{subtree:true,childList:true});boot();
})();
