import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Home,ClipboardList,Plus,User,Settings,LifeBuoy,Wallet,MapPin,ChevronRight,Bell,Search,Star,Clock,CheckCircle2,ArrowLeft,Menu,X,Send,Navigation,ShieldCheck,LogIn,LogOut,MessageCircle,Heart,RefreshCw,AlertTriangle}from'lucide-react';
import'./styles.css';
import{supabase,currentUser,signIn,signUp,signOut}from'./lib/supabase';

const demoTasks=[
{id:'demo-1',title:'Pick up documents',description:'Collect and deliver documents safely.',category:'Documents',location:'Wuse, Abuja',price:'₦8,000',budget:8000,currency:'NGN',time:'Today',distance:'4.2 km',emoji:'📄',status:'open'},
{id:'demo-2',title:'Weekly grocery shopping',description:'Shop for groceries and deliver them.',category:'Shopping',location:'Maitama, Abuja',price:'₦12,500',budget:12500,currency:'NGN',time:'Today',distance:'6.8 km',emoji:'🛒',status:'open'},
{id:'demo-3',title:'Deliver a small package',description:'Pick up a package and deliver it to the destination.',category:'Delivery',location:'Garki, Abuja',price:'₦7,500',budget:7500,currency:'NGN',time:'Tomorrow',distance:'8.1 km',emoji:'📦',status:'open'},
{id:'demo-4',title:'Help move a few boxes',description:'Help move boxes between two nearby locations.',category:'Moving',location:'Gwarinpa, Abuja',price:'₦18,000',budget:18000,currency:'NGN',time:'Sat, 10 AM',distance:'11 km',emoji:'📦',status:'open'}];
const categories=[['Shopping','🛒'],['Delivery','📦'],['Home','🏠'],['Transport','🚗'],['Documents','📄'],['Online','💻'],['Business','💼'],['Other','✨']];
const money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(n)||0);

function App(){
 const[screen,setScreen]=useState('home'),[menu,setMenu]=useState(false),[selected,setSelected]=useState(null),[modal,setModal]=useState(false),[auth,setAuth]=useState(false),[user,setUser]=useState(null),[profile,setProfile]=useState(null),[tasks,setTasks]=useState(demoTasks),[search,setSearch]=useState(''),[toast,setToast]=useState(''),[notifications,setNotifications]=useState([]),[wallet,setWallet]=useState(null),[loading,setLoading]=useState(true);
 const notify=m=>{setToast(m);window.clearTimeout(window.__egToast);window.__egToast=window.setTimeout(()=>setToast(''),2500)};
 const go=s=>{setScreen(s);setMenu(false);window.scrollTo(0,0)};
 useEffect(()=>{let mounted=true;let sub;async function boot(){try{if(supabase){const{data}=await supabase.auth.getSession();if(mounted)setUser(data.session?.user??null);const{data:listener}=supabase.auth.onAuthStateChange((_event,session)=>{if(mounted)setUser(session?.user??null)});sub=listener?.subscription}}catch(e){console.error('ErrandGo startup:',e)}finally{if(mounted)setLoading(false)}}boot();return()=>{mounted=false;sub?.unsubscribe()}},[]);
 useEffect(()=>{if(user)loadUserData();else{setProfile(null);setWallet(null);setNotifications([])}},[user]);
 useEffect(()=>{loadTasks()},[]);
 async function loadTasks(){if(!supabase){setTasks(demoTasks);return}try{const{data,error}=await supabase.from('errands').select('*,profiles:customer_id(full_name,rating,is_verified)').order('created_at',{ascending:false}).limit(100);if(error){console.error(error);setTasks([]);return}setTasks((data||[]).map(e=>({...e,location:e.pickup_address||'Location not set',price:money(e.budget),time:e.scheduled_at?new Date(e.scheduled_at).toLocaleString():'Flexible',distance:e.distance_km?`${e.distance_km} km`:'Nearby',emoji:categories.find(c=>c[0]===e.category)?.[1]||'✨'})))}catch(e){console.error(e);setTasks([])}}
 async function loadUserData(){if(!supabase||!user)return;try{const[{data:p},{data:w},{data:n}]=await Promise.all([supabase.from('profiles').select('*').eq('id',user.id).maybeSingle(),supabase.from('wallets').select('*').eq('user_id',user.id).maybeSingle(),supabase.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(20)]);setProfile(p||null);setWallet(w||null);setNotifications(n||[])}catch(e){console.error('user data:',e)}}
 async function createErrand(f){if(!user){setModal(false);setAuth(true);return}if(!supabase){notify('Supabase is not configured.');return}const{error}=await supabase.from('errands').insert({customer_id:user.id,title:f.title,description:f.description,category:f.category,budget:Number(f.price),currency:f.currency||'NGN',pickup_address:f.pickup,delivery_address:f.delivery,scheduled_at:f.scheduled?new Date(f.scheduled).toISOString():null,status:'open'});if(error)notify(error.message);else{setModal(false);notify('Errand posted successfully');loadTasks()}}
 async function applyErrand(){if(!user){setAuth(true);return}if(!supabase||!selected||selected.id.startsWith('demo')){notify('Sign in and select a live errand to apply.');return}const{error}=await supabase.from('applications').insert({errand_id:selected.id,runner_id:user.id,message:'I can complete this errand safely.',proposed_price:selected.budget});notify(error?(error.code==='23505'?'You already applied to this errand.':error.message):'Application sent to the requester')}
 async function saveTask(t){if(!user){setAuth(true);return}if(!supabase||t.id.startsWith('demo')){notify('Demo errand saved for this session.');return}const{error}=await supabase.from('saved_errands').upsert({user_id:user.id,errand_id:t.id});notify(error?error.message:'Errand saved')}
 async function logout(){await signOut();go('home');notify('Signed out')}
 const filtered=tasks.filter(t=>(`${t.title} ${t.category} ${t.location||''}`).toLowerCase().includes(search.toLowerCase()));
 if(loading)return <div className="stage"><div className="appShell"><div className="loading"><RefreshCw className="spin"/> Loading ErrandGo…</div></div></div>;
 return <div className="stage"><div className="appShell"><header className="topbar"><button className="circleBtn" onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</button><button className="brand" onClick={()=>go('home')}><span className="brandMark">E</span><span>ErrandGo</span></button><button className="circleBtn" onClick={()=>user?go('notifications'):setAuth(true)}><Bell size={19}/>{notifications.some(n=>!n.read)&&<i/>}</button></header>{menu&&<Drawer user={user} profile={profile} go={go} logout={logout} setAuth={setAuth}/>} {screen==='home'&&<HomeScreen user={user} profile={profile} go={go} setModal={setModal} tasks={filtered} saveTask={saveTask}/>} {screen==='tasks'&&<TasksScreen tasks={filtered} search={search} setSearch={setSearch} open={t=>{setSelected(t);go('detail')}}/>} {screen==='detail'&&selected&&<Detail task={selected} back={()=>go('tasks')} apply={applyErrand} save={()=>saveTask(selected)} user={user}/>} {screen==='wallet'&&<WalletScreen user={user} wallet={wallet} notify={notify} refresh={loadUserData}/>} {screen==='profile'&&<ProfileScreen user={user} profile={profile} notify={notify} logout={logout} setAuth={setAuth}/>} {screen==='notifications'&&<Notifications data={notifications}/>} {screen==='chat'&&<Chat notify={notify}/>} {screen==='admin'&&<Admin user={user} notify={notify}/>} {screen!=='detail'&&<BottomNav screen={screen} go={go} setModal={()=>user?setModal(true):setAuth(true)}/>}</div>{modal&&<PostModal close={()=>setModal(false)} save={createErrand}/>} {auth&&<AuthModal close={()=>setAuth(false)} onUser={setUser} notify={notify}/>} {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</div>;
}

function Drawer({user,profile,go,logout,setAuth}){return <div className="drawer"><div className="drawerProfile"><div className="avatar big">{(profile?.full_name||user?.email||'G')[0].toUpperCase()}</div><div><b>{profile?.full_name||user?.email||'Guest'}</b><small>{user?'Signed in':'Guest mode'}</small></div></div><button onClick={()=>go('home')}><Home/>Home</button><button onClick={()=>go('tasks')}><ClipboardList/>Find Errands</button><button onClick={()=>go('wallet')}><Wallet/>Wallet</button><button onClick={()=>go('chat')}><MessageCircle/>Messages</button><button onClick={()=>go('profile')}><User/>Profile</button>{profile?.role==='admin'&&<button onClick={()=>go('admin')}><Settings/>Admin</button>}<button onClick={()=>user?logout():setAuth(true)}>{user?<><LogOut/>Sign out</>:<><LogIn/>Sign in</>}</button></div>}
function HomeScreen({user,profile,go,setModal,tasks,saveTask}){return <main className="content homeScreen"><section className="welcome"><div><small>ERRANDGO · GLOBAL MARKETPLACE</small><h1>Hi {profile?.full_name?.split(' ')[0]||'there'} 👋</h1><p>What can we help you get done today?</p></div><div className="miniAvatar">{(profile?.full_name||'E')[0].toUpperCase()}</div></section><section className="heroCard"><div className="heroGlow"/><div className="heroCopy"><span className="pill">GET THINGS DONE</span><h2>Someone can help.<br/><strong>You just need to ask.</strong></h2><p>Post any errand and connect with a trusted person ready to get it done anywhere.</p><div className="heroActions"><button className="limeBtn" onClick={()=>user?setModal(true):null}><Plus size={18}/> Post Errand</button><button className="whiteBtn" onClick={()=>go('tasks')}>Find Errands <ChevronRight size={17}/></button></div></div><div className="heroIllustration"><div className="blob b1"/><div className="blob b2"/><div className="person">🛵</div><div className="floating f1">✓ Verified</div><div className="floating f2">₦8,000</div></div></section><section className="quickGrid"><button onClick={()=>user?setModal(true):null}><span className="qIcon purple"><Plus/></span><b>Post an Errand</b><small>Need a helping hand?</small></button><button onClick={()=>go('tasks')}><span className="qIcon green"><ClipboardList/></span><b>Find Errands</b><small>Earn by helping others</small></button><button onClick={()=>go('wallet')}><span className="qIcon orange"><Wallet/></span><b>My Wallet</b><small>Manage your earnings</small></button></section><div className="sectionTitle"><h3>Popular errands</h3><button onClick={()=>go('tasks')}>See all <ChevronRight size={15}/></button></div><div className="categoryRow">{categories.map(([n,e])=><button key={n} onClick={()=>go('tasks')}><span>{e}</span><small>{n}</small></button>)}</div><div className="sectionTitle"><h3>Errands around you</h3><button onClick={()=>go('tasks')}>View all <ChevronRight size={15}/></button></div><div className="taskList">{tasks.slice(0,4).map(t=><TaskCard key={t.id} task={t} open={()=>go('tasks')} save={()=>saveTask(t)}/>)}</div></main>}
function TaskCard({task,open,save}){return <article className="taskCard" onClick={open}><div className="taskIcon">{task.emoji||'✨'}</div><div className="taskMain"><div className="taskLine"><span>{task.category||'Other'}</span><span className="taskTime"><Clock size={12}/>{task.time||'Flexible'}</span></div><h4>{task.title}</h4><p><MapPin size={12}/>{task.location||'Location'} · {task.distance||'Nearby'}</p><div className="taskBottom"><strong>{task.price||money(task.budget)}</strong><span><Star size={12} fill="currentColor"/> {task.profiles?.rating||'5.0'}</span><button onClick={e=>{e.stopPropagation();save()}}><Heart size={16}/></button></div></div></article>}
function TasksScreen({tasks,search,setSearch,open}){return <main className="content"><div className="pageTitle"><div><small>EXPLORE</small><h2>Find errands to do</h2></div><button className="circleBtn"><MapPin size={18}/></button></div><div className="searchBar"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search errands, places or services"/></div><div className="filterRow"><button className="active">Nearby</button><button>Online</button><button>Global</button><button>Best match</button></div><div className="earnBanner"><div><span>READY TO EARN?</span><b>Turn spare time into money.</b><small>Choose an errand that works for you.</small></div><div className="earnCoin">₦</div></div><div className="sectionTitle"><h3>{tasks.length} errands available</h3></div><div className="taskList">{tasks.map(t=><TaskCard key={t.id} task={t} open={()=>open(t)} save={()=>{}}/>)}</div></main>}
function Detail({task,back,apply,save,user}){return <main className="content detail"><button className="back" onClick={back}><ArrowLeft size={19}/> Back</button><div className="detailArt"><span>{task.emoji||'✨'}</span><div className="mapDot"><Navigation/></div></div><span className="tag">{task.category}</span><h2>{task.title}</h2><div className="detailMeta"><span><MapPin/> {task.location||'Location'}</span><span><Clock/> {task.time||'Flexible'}</span></div><div className="detailPrice"><small>Budget</small><strong>{task.price||money(task.budget)}</strong><span>Secure payment protected</span></div><section className="infoCard"><h3>What needs to be done?</h3><p>{task.description||'Complete this errand carefully and follow the requester instructions.'}</p><div className="trust"><ShieldCheck/><div><b>Verified marketplace</b><small>Payments and identities are protected</small></div></div></section><button className="limeBtn fullBtn" onClick={apply}>{user?'Apply for this Errand':'Sign in to Apply'} <ChevronRight/></button><button className="whiteBtn fullBtn" onClick={save}><Heart size={16}/> Save Errand</button></main>}
function WalletScreen({user,wallet,notify,refresh}){return <main className="content"><div className="pageTitle"><div><small>MY WALLET</small><h2>Your money</h2></div><button className="circleBtn" onClick={refresh}><RefreshCw size={18}/></button></div><section className="walletCard"><span>Available balance</span><h2>{money(wallet?.balance||0)}</h2><div><small>Pending: {money(wallet?.pending_balance||0)}</small><button onClick={()=>notify(user?'Withdrawal setup is ready for provider integration.':'Sign in first')}>Withdraw</button></div></section><div className="walletActions"><button onClick={()=>notify('Payment checkout will use your configured provider.')}><Plus/>Add money</button><button onClick={()=>notify('Transaction history is stored securely in Supabase.')}><ClipboardList/>History</button></div><div className="infoCard"><h3>Protected payments</h3><p>ErrandGo uses server-side payment verification and escrow architecture. Client code cannot create money or release escrow.</p><div className="trust"><ShieldCheck/><div><b>Secure wallet</b><small>Provider webhook → server verification → transaction record</small></div></div></div></main>}
function ProfileScreen({user,profile,notify,logout,setAuth}){if(!user)return <main className="content profile"><div className="profileHead"><div className="avatar profileAvatar">E</div><h2>Join ErrandGo</h2><p>Post errands or earn by helping people.</p><button className="limeBtn" onClick={()=>setAuth(true)}>Sign in / Sign up</button></div></main>;return <main className="content profile"><div className="profileHead"><div className="avatar profileAvatar">{(profile?.full_name||user.email||'E')[0].toUpperCase()}</div><h2>{profile?.full_name||user.email}</h2><p>{user.email}</p><span className="verified"><ShieldCheck size={12}/> Verified account</span></div><div className="stats"><div><b>{profile?.completed_errands||0}</b><small>Completed</small></div><div><b>{profile?.rating||'5.0'}</b><small>Rating</small></div><div><b>{profile?.is_verified?'Yes':'Pending'}</b><small>Identity</small></div></div><div className="profileMenu"><button onClick={()=>notify('Profile editing will be connected to your profile table.')}><span><User/></span><b>Edit profile</b><ChevronRight/></button><button onClick={()=>notify('Verification center will use the identity provider.')}><span><ShieldCheck/></span><b>Verification</b><ChevronRight/></button><button onClick={()=>notify('Support center coming next.')}><span><LifeBuoy/></span><b>Help & support</b><ChevronRight/></button><button onClick={logout}><span><LogOut/></span><b>Sign out</b><ChevronRight/></button></div></main>}
function Notifications({data}){return <main className="content"><div className="pageTitle"><div><small>UPDATES</small><h2>Notifications</h2></div></div>{data.length?<div className="taskList">{data.map(n=><div className="taskCard" key={n.id}><div className="taskIcon">🔔</div><div className="taskMain"><h4>{n.title||'ErrandGo update'}</h4><p>{n.message||'You have a new notification.'}</p></div></div>)}</div>:<div className="infoCard"><h3>No notifications yet</h3><p>Important updates about your errands will appear here.</p></div>}</main>}
function Chat({notify}){return <main className="content"><div className="pageTitle"><div><small>MESSAGES</small><h2>Chat</h2></div></div><div className="infoCard"><MessageCircle size={28}/><h3>Secure errand chat</h3><p>Realtime chat is prepared for Supabase conversations and messages.</p><button className="limeBtn" onClick={()=>notify('Start or accept an errand to open chat.')}>Find an errand</button></div></main>}
function Admin({user,notify}){return <main className="content"><div className="pageTitle"><div><small>ADMIN</small><h2>Control center</h2></div></div><div className="infoCard"><AlertTriangle/><h3>Protected admin area</h3><p>{user?'Admin tools require the admin role and RLS policies.':'Sign in with an authorized admin account.'}</p><button className="limeBtn" onClick={()=>notify('Admin data will load from protected database views.')}>Refresh</button></div></main>}
function BottomNav({screen,go,setModal}){return <nav className="bottomNav"><button className={screen==='home'?'active':''} onClick={()=>go('home')}><Home/><span>Home</span></button><button className={screen==='tasks'?'active':''} onClick={()=>go('tasks')}><ClipboardList/><span>Errands</span></button><button className="postFab" onClick={setModal}><Plus size={25}/><span>Post</span></button><button className={screen==='wallet'?'active':''} onClick={()=>go('wallet')}><Wallet/><span>Wallet</span></button><button className={screen==='profile'?'active':''} onClick={()=>go('profile')}><User/><span>Profile</span></button></nav>}
function PostModal({close,save}){const[form,setForm]=useState({title:'',description:'',category:'Shopping',price:'',currency:'NGN',pickup:'',delivery:'',scheduled:''});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="overlay" onClick={e=>e.target===e.currentTarget&&close()}><div className="postModal"><button className="modalClose" onClick={close}><X/></button><span className="tag">POST AN ERRAND</span><h2>What do you need done?</h2><p>Give runners enough detail to complete your errand safely.</p><label>Title<input name="title" value={form.title} onChange={change} placeholder="e.g. Pick up my documents"/></label><label>Description<textarea name="description" value={form.description} onChange={change} placeholder="Describe what needs to be done..."/></label><div className="two"><label>Category<select name="category" value={form.category} onChange={change}>{categories.map(([n])=><option key={n}>{n}</option>)}</select></label><label>Budget<input name="price" type="number" min="1" value={form.price} onChange={change} placeholder="8000"/></label></div><div className="two"><label>Pickup<input name="pickup" value={form.pickup} onChange={change} placeholder="Pickup location"/></label><label>Delivery<input name="delivery" value={form.delivery} onChange={change} placeholder="Destination"/></label></div><button className="limeBtn fullBtn" disabled={!form.title||!form.price} onClick={()=>save(form)}>Publish Errand <Send size={16}/></button></div></div>}
function AuthModal({close,onUser,notify}){const[mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);try{const result=mode==='login'?await signIn(email,password):await signUp(email,password,{full_name:email.split('@')[0]});if(result.error)notify(result.error.message);else{if(result.data?.user)onUser(result.data.user);notify(mode==='login'?'Welcome back!':'Account created. Check your email if confirmation is required.');close()}}catch(e){notify(e.message||'Authentication failed')}finally{setBusy(false)}}return <div className="overlay" onClick={e=>e.target===e.currentTarget&&close()}><form className="postModal" onSubmit={submit}><button type="button" className="modalClose" onClick={close}><X/></button><span className="tag">ERRANDGO ACCOUNT</span><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p>Use one account to post errands and earn by completing them.</p><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" required minLength="6" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></label><button className="limeBtn fullBtn" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'} <LogIn size={16}/></button><button type="button" className="whiteBtn fullBtn" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Create a new account':'I already have an account'}</button></form></div>}

createRoot(document.getElementById('root')).render(<App/>);
